import { createContext, useContext, useState, useEffect } from 'react'

const translations = {
  en: {
    welcome: 'Welcome',
    selectLangContext: 'Please select your preferred language to continue.',
    selectService: 'Select Service Category',
    howCanWeHelp: 'What can we help you with today?',
    electricity: 'Electricity Services',
    water: 'Water Department',
    gas: 'Gas Supply',
    sanitation: 'Sanitation',
    municipal: 'Municipal Corp.',
    otherDept: 'Other Dept.',
    otherDeptDesc: 'Access more departments',
    registerComplaint: 'Register Complaint',
    reportGrievance: 'Report Grievance via QR Scan',
    fastTrack: 'Fast Track',
    light: 'Light',
    dark: 'Dark',
    back: 'Back',
    whatReport: 'What would you like to report?',
    selectCategory: 'Select the category that best matches your complaint',
    road: 'Road & Infrastructure',
    waterSupply: 'Water Supply',
    streetLight: 'Street Lighting',
    sanitationWaste: 'Sanitation & Waste',
    safety: 'Public Safety',
    noise: 'Noise Pollution',
    parks: 'Parks & Green Spaces',
    other: 'Other Issues',
    complaintRouteInfo: 'Your complaint will be routed to the appropriate municipal department',
    serviceNotFound: 'Service Not Found',
    goBack: 'Go Back',
    payBill: 'Pay Bill',
    viewHistory: 'View Usage/History',
    newConnection: 'New Connection',
    lodgeComplaint: 'Lodge Complaint',
    loadExtension: 'Load Extension',
    meterReplacement: 'Meter Replacement',
    updateCredentials: 'Update Credentials',
    trackStatus: 'Track Status',
    meterServices: 'Meter Services',
    propertyTax: 'Property Tax',
    accessYour: 'Access your',
    tapActionToProceed: 'Please tap an action on the left to proceed.',
    promptToScan: 'You may be prompted to scan your ID card or enter your consumer number.',
    identityVerification: 'Identity Verification',
    enterAadhar: 'Please enter your 12-digit Aadhar Card Number for e-KYC.',
    verifyBiometrics: 'Verify via Biometrics',
    linkMobile: 'Link Mobile Number',
    needMobile: 'We need this number for sending OTPs and application updates.',
    enter10Digits: 'Enter 10 Digits',
    submitApplication: 'Submit Application',
    submitting: 'Submitting...',
    creatingProfile: 'Creating your profile and updating records.',
    applicationReceived: 'Application Received',
    requestRegistered: 'Your request has been successfully registered.',
    appRefNo: 'Application Reference No',
    returnHome: 'Return to Home',
    enterId: 'Enter ID',
    enterWait: 'Please enter your unique 6+ digit ID shown on your previous bill.',
    enterNumber: 'Enter Number',
    fetchBill: 'Fetch Bill Details',
    fetchingBill: 'Fetching Bill details...',
    amountDue: 'Amount Due',
    dueDate: 'Due Date',
    billCycle: 'Bill Cycle',
    selectPayment: 'Select Payment Method',
    upiQr: 'UPI / QR Scan',
    cardPayment: 'Card Payment',
    scanQrToPay: 'Scan QR to Pay',
    scanUpi: 'Scan with any UPI app (GPay, PhonePe, Paytm)',
    waitingPayment: 'Waiting for payment confirmation...',
    insertTapCard: 'Insert or Tap Card',
    followTerminal: 'Please follow the instructions on the card terminal.',
    processingSecure: 'Processing secure transaction...'
  },
  hi: {
    welcome: 'स्वागत',
    selectLangContext: 'जारी रखने के लिए कृपया अपनी पसंदीदा भाषा चुनें।',
    selectService: 'सेवा श्रेणी चुनें',
    howCanWeHelp: 'आज हम आपकी क्या मदद कर सकते हैं?',
    electricity: 'बिजली सेवाएं',
    water: 'जल विभाग',
    gas: 'गैस आपूर्ति',
    sanitation: 'स्वच्छता',
    municipal: 'नगर निगम',
    otherDept: 'अन्य विभाग',
    otherDeptDesc: 'अधिक विभागों तक पहुँचें',
    registerComplaint: 'शिकायत दर्ज करें',
    reportGrievance: 'क्यूआर स्कैन के माध्यम से शिकायत दर्ज करें',
    fastTrack: 'फास्ट ट्रैक',
    light: 'प्रकाश',
    dark: 'अंधेरा',
    back: 'वापस',
    whatReport: 'आप क्या रिपोर्ट करना चाहेंगे?',
    selectCategory: 'वह श्रेणी चुनें जो आपकी शिकायत से सबसे अच्छी तरह मेल खाती हो',
    road: 'सड़क और बुनियादी ढांचा',
    waterSupply: 'जल आपूर्ति',
    streetLight: 'स्ट्रीट लाइटिंग',
    sanitationWaste: 'स्वच्छता और अपशिष्ट',
    safety: 'सार्वजनिक सुरक्षा',
    noise: 'ध्वनि प्रदूषण',
    parks: 'पार्क और हरे भरे स्थान',
    other: 'अन्य मुद्दे',
    complaintRouteInfo: 'आपकी शिकायत उचित नगरपालिका विभाग को भेजी जाएगी',
    serviceNotFound: 'सेवा नहीं मिली',
    goBack: 'वापस जाओ',
    payBill: 'बिल का भुगतान करें',
    viewHistory: 'उपयोग/इतिहास देखें',
    newConnection: 'नया कनेक्शन',
    lodgeComplaint: 'शिकायत दर्ज करें',
    loadExtension: 'लोड विस्तार',
    meterReplacement: 'मीटर बदलना',
    updateCredentials: 'प्रमाण अपडेट करें',
    trackStatus: 'स्थिति ट्रैक करें',
    meterServices: 'मीटर सेवाएं',
    propertyTax: 'संपत्ति कर',
    accessYour: 'अपनी/अपना एक्सेस करें ',
    tapActionToProceed: 'आगे बढ़ने के लिए कृपया बाईं ओर किसी क्रिया पर टैप करें।',
    promptToScan: 'आपको अपना आईडी कार्ड स्कैन करने या अपना उपभोक्ता नंबर दर्ज करने के लिए कहा जा सकता है।',
    identityVerification: 'पहचान सत्यापन',
    enterAadhar: 'ई-केवाईसी के लिए कृपया अपना 12 अंकों का आधार कार्ड नंबर दर्ज करें।',
    verifyBiometrics: 'बायोमेट्रिक्स के माध्यम से सत्यापित करें',
    linkMobile: 'मोबाइल नंबर लिंक करें',
    needMobile: 'हमें ओटीपी और एप्लिकेशन अपडेट भेजने के लिए इस नंबर की आवश्यकता है।',
    enter10Digits: '10 अंक दर्ज करें',
    submitApplication: 'आवेदन जमा करें',
    submitting: 'जमा किया जा रहा है...',
    creatingProfile: 'आपकी प्रोफ़ाइल बन रही है और रिकॉर्ड अपडेट हो रहे हैं।',
    applicationReceived: 'आवेदन प्राप्त हुआ',
    requestRegistered: 'आपका अनुरोध सफलतापूर्वक पंजीकृत कर लिया गया है।',
    appRefNo: 'आवेदन संदर्भ संख्या',
    returnHome: 'होम पर लौटें',
    enterId: 'दर्ज करें',
    enterWait: 'कृपया अपने पिछले बिल पर दिखाया गया विशिष्ट 6+ अंकों का आईडी दर्ज करें।',
    enterNumber: 'नंबर दर्ज करें',
    fetchBill: 'बिल विवरण प्राप्त करें',
    fetchingBill: 'बिल विवरण प्राप्त किया जा रहा है...',
    amountDue: 'देय राशि',
    dueDate: "नियत तारीख",
    billCycle: "बिल चक्र",
    selectPayment: "भुगतान विधि चुनें",
    upiQr: "UPI / QR स्कैन",
    cardPayment: "कार्ड भुगतान",
    scanQrToPay: "भुगतान के लिए QR स्कैन करें",
    scanUpi: "किसी भी UPI ऐप से स्कैन करें (GPay, PhonePe, Paytm)",
    waitingPayment: "भुगतान पुष्टि की प्रतीक्षा है...",
    insertTapCard: "कार्ड डालें या टैप करें",
    followTerminal: "कृपया कार्ड टर्मिनल पर निर्देशों का पालन करें।",
    processingSecure: "सुरक्षित लेनदेन की प्रक्रिया हो रही है..."
  },
  as: {
    welcome: 'স্বাগতম',
    selectLangContext: 'আগবাঢ়িবলৈ অনুগ্ৰহ কৰি আপোনাৰ পছন্দৰ ভাষা বাছনি কৰক।',
    selectService: 'সেৱা শ্ৰেণী বাছক',
    howCanWeHelp: 'আজি আমি আপোনাক কিদৰে সহায় কৰিব পাৰোঁ?',
    electricity: 'বিদ্যুৎ সেৱা',
    water: 'জল বিভাগ',
    gas: 'গেছ যোগান',
    sanitation: 'অনাময়',
    municipal: 'পৌৰ নিগম',
    otherDept: 'অন্যান্য বিভাগ',
    otherDeptDesc: 'অধিক বিভাগসমূহ চাওক',
    registerComplaint: 'অভিযোগ পঞ্জীয়ন কৰক',
    reportGrievance: 'কিউআৰ স্কেনৰ জৰিয়তে অভিযোগ দাখিল কৰক',
    fastTrack: 'ফাষ্ট ট্ৰেক',
    light: 'পোহৰ',
    dark: 'আন্ধাৰ',
    back: 'উভতি যাওক',
    whatReport: "আপুনি কি অভিযোগ কৰিব বিচাৰে?",
    selectCategory: "আপোনাৰ অভিযোগৰ সৈতে সৰ্বোত্তমভাৱে মিলি যোৱা শ্ৰেণীটো বাছনি কৰক",
    road: "ৰাস্তা আৰু আন্তঃগাঁথনি",
    waterSupply: "পানী যোগান",
    streetLight: "ৰাস্তাৰ পোহৰ",
    sanitationWaste: "অনাময় আৰু আৱৰ্জনা",
    safety: "ৰাজহুৱা নিৰাপত্তা",
    noise: "শব্দ প্ৰদূষণ",
    parks: "উদ্যান আৰু সেউজীয়া স্থান",
    other: "অন্যান্য বিষয়সমূহ",
    complaintRouteInfo: "আপোনাৰ অভিযোগ উপযুক্ত পৌৰ নিগমৰ বিভাগলৈ প্ৰেৰণ কৰা হ'ব",
    serviceNotFound: "সেৱা পোৱা হোৱা নাই",
    goBack: "উভতি যাওক",
    payBill: "বিল পৰিশোধ কৰক",
    viewHistory: "ব্যৱহাৰ/ইতিহাস চাওক",
    newConnection: "নতুন সংযোগ",
    lodgeComplaint: "অভিযোগ দাখিল কৰক",
    loadExtension: "লোড সম্প্ৰসাৰণ",
    meterReplacement: "মিটাৰ সলনি",
    updateCredentials: "তথ্য আপডেট কৰক",
    trackStatus: "স্থিতি চাওক",
    meterServices: "মিটাৰ সেৱা",
    propertyTax: "সম্পত্তি কৰ",
    accessYour: "আপোনাৰ প্ৰৱেশ কৰক ",
    tapActionToProceed: "আগবাঢ়িবলৈ অনুগ্ৰহ কৰি বাওঁফালৰ কোনো কাৰ্য্যত টেপ কৰক।",
    promptToScan: "আপোনাক আপোনাৰ আইডি কাৰ্ড স্কেন কৰিবলৈ বা আপোনাৰ উপভোক্তা নম্বৰ প্ৰৱেশ কৰিবলৈ কোৱা হ'ব পাৰে।",
    identityVerification: "পৰিচয় প্ৰমাণীকৰণ",
    enterAadhar: "ই-কেৱাইচিৰ বাবে অনুগ্ৰহ কৰি আপোনাৰ ১২-অংকৰ আধাৰ কাৰ্ড নম্বৰ প্ৰৱেশ কৰক।",
    verifyBiometrics: "বায়োমেট্ৰিকৰ জৰিয়তে প্ৰমাণিত কৰক",
    linkMobile: "ম'বাইল নম্বৰ লিংক কৰক",
    needMobile: "অ'টিপি আৰু আৱেদনৰ আপডেট প্ৰেৰণৰ বাবে আমাক এই নম্বৰটোৰ প্ৰয়োজন।",
    enter10Digits: "১০টা অংক প্ৰৱেশ কৰক",
    submitApplication: "আবেদন দাখিল কৰক",
    submitting: "দাখিল কৰা হৈছে...",
    creatingProfile: "আপোনাৰ প্ৰফাইল সৃষ্টি কৰা হৈছে আৰু ৰেকৰ্ড আপডেট কৰা হৈছে।",
    applicationReceived: "আবেদন গ্ৰহণ কৰা হৈছে",
    requestRegistered: "আপোনাৰ অনুৰোধ সফলতাৰে পঞ্জীয়ন কৰা হৈছে।",
    appRefNo: "আবেদনৰ প্ৰসংগ নম্বৰ",
    returnHome: "গৃহ পৃষ্ঠালৈ ঘূৰি যাওক",
    enterId: "প্ৰৱেশ কৰক",
    enterWait: "অনুগ্ৰহ কৰি আপোনাৰ পূৰ্বৰ বিলত দেখুওৱা অনন্য ৬+ অংকৰ আইডি প্ৰৱেশ কৰক।",
    enterNumber: "नনম্বৰ প্ৰৱেশ কৰক",
    fetchBill: "বিলৰ বিৱৰণ আনক",
    fetchingBill: "বিলৰ বিৱৰণ অনা হৈছে...",
    amountDue: "পৰিশোধ কৰিবলগীয়া পৰিমাণ",
    dueDate: "নিৰ্ধাৰিত তাৰিখ",
    billCycle: "বিল চক্ৰ",
    selectPayment: "পৰিশোধৰ পদ্ধতি বাছনি কৰক",
    upiQr: "ইউপিআই / কিউআৰ স্কেন",
    cardPayment: "কাৰ্ডৰ জৰিয়তে পৰিশোধ",
    scanQrToPay: "পৰিশোধ কৰিবলৈ কিউআৰ স্কেন কৰক",
    scanUpi: "যিকোনো ইউপিআই এপৰ সৈতে স্কেন কৰক (জি-পে, ফ'ন-পে, পেটিএম)",
    waitingPayment: "পৰিশোধৰ নিশ্চিতকৰণৰ বাবে আপেক্ষা কৰা হৈছে...",
    insertTapCard: "কাৰ্ড সুমুৱাই দিয়ক বা টেপ কৰক",
    followTerminal: "অনুগ্ৰহ কৰি কাৰ্ড টাৰ্মিনেলত দিয়া নিৰ্দেশনাসমূহ অনুসৰণ কৰক।",
    processingSecure: "সুৰক্ষিত লেনদেন প্ৰক্ৰিয়াকৰণ কৰা হৈছে..."
  },
  kn: {
    welcome: 'ಸ್ವಾಗತ',
    selectLangContext: 'ಮುಂದುವರಿಯಲು ದಯವಿಟ್ಟು ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ.',
    selectService: 'ಸೇವಾ ವರ್ಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    howCanWeHelp: 'ಇಂದು ನಾವು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?',
    electricity: 'ವಿದ್ಯುತ್ ಸೇವೆಗಳು',
    water: 'ಜಲ ವಿಭಾಗ',
    gas: 'ಗ್ಯಾಸ್ ಪೂರೈಕೆ',
    sanitation: 'ನೈರ್ಮಲ್ಯ',
    municipal: 'ಪುರಸಭೆ',
    otherDept: 'ಇತರ ಇಲಾಖೆ',
    otherDeptDesc: 'ಹೆಚ್ಚಿನ ಇಲಾಖೆಗಳನ್ನು ಪ್ರವೇಶಿಸಿ',
    registerComplaint: 'ದೂರು ನೋಂದಾಯಿಸಿ',
    reportGrievance: 'QR ಸ್ಕ್ಯಾನ್ ಮೂಲಕ ಕುಂದುಕೊರತೆ ವರದಿ ಮಾಡಿ',
    fastTrack: 'ಫಾಸ್ಟ್ ಟ್ರ್ಯಾಕ್',
    light: 'ಬೆಳಕು',
    dark: 'ಕತ್ತಲೆ',
    back: 'ಹಿಂದೆ',
    whatReport: 'ನೀವು ಏನನ್ನು ವರದಿ ಮಾಡಲು ಬಯಸುತ್ತೀರಿ?',
    selectCategory: 'ನಿಮ್ಮ ದೂರಿಗೆ ಸೂಕ್ತವಾದ ವರ್ಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    road: 'ರಸ್ತೆ ಮತ್ತು ಮೂಲಸೌಕರ್ಯ',
    waterSupply: 'ನೀರು ಸರಬರಾಜು',
    streetLight: 'ಬೀದಿ ದೀಪ',
    sanitationWaste: 'ನೈರ್ಮಲ್ಯ ಮತ್ತು ತ್ಯಾಜ್ಯ',
    safety: 'ಸಾರ್ವಜನಿಕ ಸುರಕ್ಷತೆ',
    noise: 'ಶಬ್ದ ಮಾಲಿನ್ಯ',
    parks: 'ಉದ್ಯಾನವನಗಳು ಮತ್ತು ಹಸಿರು ಸ್ಥಳಗಳು',
    other: 'ಇತರ ಸಮಸ್ಯೆಗಳು',
    complaintRouteInfo: 'ನಿಮ್ಮ ದೂರನ್ನು ಸೂಕ್ತ ಪುರಸಭೆ ಇಲಾಖೆಗೆ ರವಾನಿಸಲಾಗುತ್ತದೆ',
    serviceNotFound: 'ಸೇವೆ ಕಂಡುಬಂದಿಲ್ಲ',
    goBack: 'ಹಿಂದೆ ಹೋಗಿ',
    payBill: 'ಬಿಲ್ ಪಾವತಿಸಿ',
    viewHistory: 'ಬಳಕೆ/ಇತಿಹಾಸ ವೀಕ್ಷಿಸಿ',
    newConnection: 'ಹೊಸ ಸಂಪರ್ಕ',
    lodgeComplaint: 'ದೂರು ದಾಖಲಿಸಿ',
    loadExtension: 'ಲೋಡ್ ವಿಸ್ತರಣೆ',
    meterReplacement: 'ಮೀಟರ್ ಬದಲಿ',
    updateCredentials: 'ರುಜುವಾತುಗಳನ್ನು ನವೀಕರಿಸಿ',
    trackStatus: 'ಸ್ಥಿತಿಯನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    meterServices: 'ಮೀಟರ್ ಸೇವೆಗಳು',
    propertyTax: 'ಆಸ್ತಿ ತೆರಿಗೆ',
    accessYour: 'ನಿಮ್ಮ ಪ್ರವೇಶಿಸಿ',
    tapActionToProceed: 'ಮುಂದುವರಿಯಲು ದಯವಿಟ್ಟು ಎಡಭಾಗದಲ್ಲಿರುವ ಕ್ರಿಯೆಯನ್ನು ಟ್ಯಾಪ್ ಮಾಡಿ.',
    promptToScan: 'ನಿಮ್ಮ ಗುರುತಿನ ಚೀಟಿಯನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಲು ಅಥವಾ ನಿಮ್ಮ ಗ್ರಾಹಕ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಲು ನಿಮ್ಮನ್ನು ಕೇಳಬಹುದು.',
    identityVerification: 'ಗುರುತು ಪರಿಶೀಲನೆ',
    enterAadhar: 'ಇ-ಕೆವೈಸಿಗಾಗಿ ದಯವಿಟ್ಟು ನಿಮ್ಮ 12-ಅಂಕಿಯ ಆಧಾರ್ ಕಾರ್ಡ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ.',
    verifyBiometrics: 'ಬಯೋಮೆಟ್ರಿಕ್ಸ್ ಮೂಲಕ ಪರಿಶೀಲಿಸಿ',
    linkMobile: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ಲಿಂಕ್ ಮಾಡಿ',
    needMobile: 'OTP ಗಳು ಮತ್ತು ಅಪ್ಲಿಕೇಶನ್ ನವೀಕರಣಗಳನ್ನು ಕಳುಹಿಸಲು ನಮಗೆ ಈ ಸಂಖ್ಯೆ ಅಗತ್ಯವಿದೆ.',
    enter10Digits: '10 ಅಂಕೆಗಳನ್ನು ನಮೂದಿಸಿ',
    submitApplication: 'ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    submitting: 'ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...',
    creatingProfile: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ರಚಿಸಲಾಗುತ್ತಿದೆ ಮತ್ತು ದಾಖಲೆಗಳನ್ನು ನವೀಕರಿಸಲಾಗುತ್ತಿದೆ.',
    applicationReceived: 'ಅರ್ಜಿ ಸ್ವೀಕರಿಸಲಾಗಿದೆ',
    requestRegistered: 'ನಿಮ್ಮ ವಿನಂತಿಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ನೋಂದಾಯಿಸಲಾಗಿದೆ.',
    appRefNo: 'ಅಪ್ಲಿಕೇಶನ್ ಉಲ್ಲೇಖ ಸಂಖ್ಯೆ',
    returnHome: 'ಮುಖಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ',
    enterId: 'ನಮೂದಿಸಿ',
    enterWait: 'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಹಿಂದಿನ ಬಿಲ್‌ನಲ್ಲಿರುವ ನಿಮ್ಮ ಅನನ್ಯ 6+ ಅಂಕಿಯ ಐಡಿಯನ್ನು ನಮೂದಿಸಿ.',
    enterNumber: 'ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
    fetchBill: 'ಬಿಲ್ ವಿವರಗಳನ್ನು ಪಡೆಯಿರಿ',
    fetchingBill: 'ಬಿಲ್ ವಿವರಗಳನ್ನು ಪಡೆಯಲಾಗುತ್ತಿದೆ...',
    amountDue: 'ಬಾಕಿ ಇರುವ ಮೊತ್ತ',
    dueDate: "ಗಡುವು ದಿನಾಂಕ",
    billCycle: "ಬಿಲ್ ಚಕ್ರ",
    selectPayment: "ಪಾವತಿ ವಿಧಾನವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    upiQr: "UPI / QR ಸ್ಕ್ಯಾನ್",
    cardPayment: "ಕಾರ್ಡ್ ಪಾವತಿ",
    scanQrToPay: "ಪಾವತಿಸಲು QR ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
    scanUpi: "ಯಾವುದೇ UPI ಅಪ್ಲಿಕೇಶನ್‌ನೊಂದಿಗೆ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ (GPay, PhonePe, Paytm)",
    waitingPayment: "ಪಾವತಿ ದೃಢೀಕರಣಕ್ಕಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ...",
    insertTapCard: "ಕಾರ್ಡ್ ಸೇರಿಸಿ ಅಥವಾ ಟ್ಯಾಪ್ ಮಾಡಿ",
    followTerminal: "ದಯವಿಟ್ಟು ಕಾರ್ಡ್ ಟರ್ಮಿನಲ್‌ನಲ್ಲಿರುವ ಸೂಚನೆಗಳನ್ನು ಅನುಸರಿಸಿ.",
    processingSecure: "ಸುರಕ್ಷಿತ ವಹಿವಾಟನ್ನು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ..."
  }
}

const LanguageContext = createContext()

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('kiosk-lang') || 'en'
  })

  useEffect(() => {
    document.documentElement.lang = lang
    localStorage.setItem('kiosk-lang', lang)
  }, [lang])

  const t = (key) => {
    return translations[lang]?.[key] || translations['en'][key] || key
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
