const Map<String, String> asStrings = {
  // General
  'app_name': 'URBAN',
  'app_tagline': 'ৰিপ\'ৰ্ট কৰক। সমাধান কৰক। উন্নত কৰক।',
  'select_language': 'ভাষা নিৰ্বাচন কৰক',
  'get_started': 'আৰম্ভ কৰক',
  'skip': 'এৰি যাওক',
  'next': 'পৰৱৰ্তী',
  'back': 'পিছলৈ',
  'confirm': 'নিশ্চিত কৰক',
  'cancel': 'বাতিল কৰক',
  'edit': 'সম্পাদনা',
  'save': 'সংৰক্ষণ কৰক',
  'delete': 'মচি পেলাওক',
  'retry': 'পুনৰ চেষ্টা কৰক',
  'loading': 'ল\'ড হৈ আছে...',
  'error': 'কিবা ভুল হৈছে',
  'success': 'সফল!',
  'no_internet': 'ইণ্টাৰনেট সংযোগ নাই',
  'saved_offline': 'অফলাইনত সংৰক্ষিত। সংযোগ হ\'লে ছিংক হ\'ব।',

  // Auth
  'login_title': 'URBAN-লৈ স্বাগতম',
  'enter_phone': 'আপোনাৰ ম\'বাইল নম্বৰ দিয়ক',
  'send_otp': 'OTP পঠিয়াওক',
  'enter_otp': 'সত্যাপন ক\'ড দিয়ক',
  'verify_otp': 'OTP সত্যাপন কৰক',
  'resend_otp': 'OTP পুনৰ পঠিয়াওক',
  'phone_hint': 'ম\'বাইল নম্বৰ',
  'invalid_phone': 'অনুগ্ৰহ কৰি এটা বৈধ ১০ সংখ্যাৰ নম্বৰ দিয়ক',

  // Onboarding
  'onboard_title_1': 'তৎক্ষণাত সমস্যা ৰিপ\'ৰ্ট কৰক',
  'onboard_desc_1': 'যিকোনো নাগৰিক সমস্যাৰ ফট\' তুলক — গাঁত, আৱৰ্জনা, ভগা ষ্ট্ৰীটলাইট আদি।',
  'onboard_title_2': 'AI-এ সমস্যা চিনাক্ত কৰে',
  'onboard_desc_2': 'আমাৰ AI-এ স্বয়ংক্ৰিয়ভাৱে সমস্যাৰ ধৰণ চিনাক্ত কৰে, সঠিক বিভাগলৈ প্ৰেৰণ কৰে, আৰু অগ্ৰাধিকাৰ নিৰ্ধাৰণ কৰে।',
  'onboard_title_3': 'কিয়স্কৰ জৰিয়তে দ্ৰুত দাখিল',
  'onboard_desc_3': 'QR ক\'ড সৃষ্টি কৰক আৰু আপোনাৰ অভিযোগ আনুষ্ঠানিকভাৱে দাখিল কৰিবলৈ ওচৰৰ কিয়স্কত স্কেন কৰক।',

  // Home
  'home': 'হ\'ম',
  'hello': 'নমস্কাৰ',
  'report_issue': 'সমস্যা ৰিপ\'ৰ্ট কৰক',
  'my_complaints': 'মোৰ অভিযোগ',
  'notifications': 'জাননী',
  'help_chatbot': 'সহায় / চেটবট',
  'profile': 'প্ৰ\'ফাইল',
  'recent_complaints': 'শেহতীয়া অভিযোগ',

  // Report Flow
  'capture_image': 'ফট\' তুলক',
  'take_photo': 'ফট\' তুলক',
  'upload_gallery': 'গেলেৰীৰ পৰা আপল\'ড কৰক',
  'analyzing_issue': 'সমস্যা বিশ্লেষণ হৈ আছে...',
  'ai_result': 'বিশ্লেষণ ফলাফল',
  'detected_issue': 'চিনাক্ত সমস্যা',
  'department': 'বিভাগ',
  'priority': 'অগ্ৰাধিকাৰ',
  'confidence': 'নিশ্চিততা',
  'description': 'বিৱৰণ',
  'add_notes': 'অতিৰিক্ত টোকা যোগ কৰক...',
  'confirm_location': 'স্থান নিশ্চিত কৰক',
  'adjust_pin': 'স্থান সামঞ্জস্য কৰিবলৈ পিন টানক',
  'add_landmark': 'লেণ্ডমাৰ্ক যোগ কৰক (ঐচ্ছিক)',
  'complaint_draft': 'অভিযোগ সাৰাংশ',
  'generate_qr': 'QR ক\'ড সৃষ্টি কৰক',
  'save_draft': 'ড্ৰাফ্ট সংৰক্ষণ কৰক',
  'qr_instructions': 'কিয়স্ক দাখিল',
  'qr_message': 'এই অভিযোগ দাখিল কৰিবলৈ, ওচৰৰ কিয়স্কলৈ যাওক আৰু QR ক\'ড স্কেন কৰক।',
  'regenerate_qr': 'QR পুনৰ সৃষ্টি কৰক',
  'retake_photo': 'পুনৰ ফট\' তুলক',

  // Complaints
  'all_complaints': 'সকলো',
  'pending': 'বাকী আছে',
  'in_progress': 'প্ৰগতিত',
  'resolved': 'সমাধান হৈছে',
  'draft': 'ড্ৰাফ্ট',
  'no_complaints': 'এতিয়ালৈকে কোনো অভিযোগ নাই',
  'complaint_details': 'অভিযোগৰ বিৱৰণ',
  'timeline': 'সময়ৰেখা',

  // Profile
  'name': 'নাম',
  'mobile_number': 'ম\'বাইল নম্বৰ',
  'address': 'ঠিকনা',
  'edit_profile': 'প্ৰ\'ফাইল সম্পাদনা কৰক',
  'change_language': 'ভাষা সলনি কৰক',
  'logout': 'লগআউট',
  'logout_confirm': 'আপুনি সঁচাকৈ লগআউট কৰিব বিচাৰে নেকি?',

  // Chatbot
  'chatbot_greeting': 'নমস্কাৰ! মই আপোনাৰ URBAN সহায়ক। আজি মই আপোনাক কেনেকৈ সহায় কৰিব পাৰোঁ?',
  'type_message': 'বাৰ্তা লিখক...',
};
