const Map<String, String> enStrings = {
  // General
  'app_name': 'URBAN',
  'app_tagline': 'Report. Resolve. Improve.',
  'select_language': 'Select Language',
  'get_started': 'Get Started',
  'skip': 'Skip',
  'next': 'Next',
  'back': 'Back',
  'confirm': 'Confirm',
  'cancel': 'Cancel',
  'edit': 'Edit',
  'save': 'Save',
  'delete': 'Delete',
  'retry': 'Retry',
  'loading': 'Loading...',
  'error': 'Something went wrong',
  'success': 'Success!',
  'no_internet': 'No internet connection',
  'saved_offline': 'Saved offline. Will sync when connected.',

  // Auth
  'login_title': 'Welcome to URBAN',
  'enter_phone': 'Enter your mobile number',
  'send_otp': 'Send OTP',
  'enter_otp': 'Enter verification code',
  'verify_otp': 'Verify OTP',
  'resend_otp': 'Resend OTP',
  'phone_hint': 'Mobile Number',
  'invalid_phone': 'Please enter a valid 10-digit number',

  // Onboarding
  'onboard_title_1': 'Report Issues Instantly',
  'onboard_desc_1': 'Take a photo of any civic issue you see — potholes, garbage, broken streetlights, and more.',
  'onboard_title_2': 'AI Detects the Problem',
  'onboard_desc_2': 'Our AI automatically identifies the issue type, assigns the right department, and sets priority.',
  'onboard_title_3': 'Quick Submission via Kiosk',
  'onboard_desc_3': 'Generate a QR code and scan it at a nearby kiosk to officially submit your complaint.',

  // Home
  'home': 'Home',
  'hello': 'Hello',
  'report_issue': 'Report Issue',
  'my_complaints': 'My Complaints',
  'notifications': 'Notifications',
  'help_chatbot': 'Help / Chatbot',
  'profile': 'Profile',
  'recent_complaints': 'Recent Complaints',

  // Report Flow
  'capture_image': 'Capture Image',
  'take_photo': 'Take Photo',
  'upload_gallery': 'Upload from Gallery',
  'analyzing_issue': 'Analyzing Issue...',
  'ai_result': 'Analysis Result',
  'detected_issue': 'Detected Issue',
  'department': 'Department',
  'priority': 'Priority',
  'confidence': 'Confidence',
  'description': 'Description',
  'add_notes': 'Add extra notes...',
  'confirm_location': 'Confirm Location',
  'adjust_pin': 'Drag pin to adjust location',
  'add_landmark': 'Add landmark (optional)',
  'complaint_draft': 'Complaint Summary',
  'generate_qr': 'Generate QR Code',
  'save_draft': 'Save Draft',
  'qr_instructions': 'Kiosk Submission',
  'qr_message': 'To submit this complaint, visit a nearby kiosk and scan the QR code.',
  'regenerate_qr': 'Regenerate QR',
  'retake_photo': 'Retake Photo',

  // Complaints
  'all_complaints': 'All',
  'pending': 'Pending',
  'in_progress': 'In Progress',
  'resolved': 'Resolved',
  'draft': 'Draft',
  'no_complaints': 'No complaints yet',
  'complaint_details': 'Complaint Details',
  'timeline': 'Timeline',

  // Profile
  'name': 'Name',
  'mobile_number': 'Mobile Number',
  'address': 'Address',
  'edit_profile': 'Edit Profile',
  'change_language': 'Change Language',
  'logout': 'Logout',
  'logout_confirm': 'Are you sure you want to logout?',

  // Chatbot
  'chatbot_greeting': 'Hi! I\'m your URBAN assistant. How can I help you today?',
  'type_message': 'Type a message...',
};
