const Map<String, String> hiStrings = {
  // General
  'app_name': 'URBAN',
  'app_tagline': 'रिपोर्ट करें। समाधान पाएं। सुधार करें।',
  'select_language': 'भाषा चुनें',
  'get_started': 'शुरू करें',
  'skip': 'छोड़ें',
  'next': 'अगला',
  'back': 'पीछे',
  'confirm': 'पुष्टि करें',
  'cancel': 'रद्द करें',
  'edit': 'संपादित करें',
  'save': 'सहेजें',
  'delete': 'हटाएं',
  'retry': 'पुनः प्रयास',
  'loading': 'लोड हो रहा है...',
  'error': 'कुछ गलत हो गया',
  'success': 'सफल!',
  'no_internet': 'इंटरनेट कनेक्शन नहीं है',
  'saved_offline': 'ऑफ़लाइन सहेजा गया। कनेक्ट होने पर सिंक होगा।',

  // Auth
  'login_title': 'URBAN में आपका स्वागत है',
  'enter_phone': 'अपना मोबाइल नंबर दर्ज करें',
  'send_otp': 'OTP भेजें',
  'enter_otp': 'सत्यापन कोड दर्ज करें',
  'verify_otp': 'OTP सत्यापित करें',
  'resend_otp': 'OTP पुनः भेजें',
  'phone_hint': 'मोबाइल नंबर',
  'invalid_phone': 'कृपया एक मान्य 10 अंकों का नंबर दर्ज करें',

  // Onboarding
  'onboard_title_1': 'तुरंत समस्या रिपोर्ट करें',
  'onboard_desc_1': 'किसी भी नागरिक समस्या की फोटो लें — गड्ढे, कचरा, टूटी स्ट्रीटलाइट और बहुत कुछ।',
  'onboard_title_2': 'AI समस्या पहचानता है',
  'onboard_desc_2': 'हमारा AI स्वचालित रूप से समस्या के प्रकार की पहचान करता है, सही विभाग को सौंपता है, और प्राथमिकता निर्धारित करता है।',
  'onboard_title_3': 'कियोस्क से त्वरित सबमिशन',
  'onboard_desc_3': 'QR कोड जनरेट करें और अपनी शिकायत आधिकारिक रूप से दर्ज करने के लिए निकटतम कियोस्क पर स्कैन करें।',

  // Home
  'home': 'होम',
  'hello': 'नमस्ते',
  'report_issue': 'समस्या रिपोर्ट करें',
  'my_complaints': 'मेरी शिकायतें',
  'notifications': 'सूचनाएं',
  'help_chatbot': 'सहायता / चैटबॉट',
  'profile': 'प्रोफ़ाइल',
  'recent_complaints': 'हालिया शिकायतें',

  // Report Flow
  'capture_image': 'फ़ोटो लें',
  'take_photo': 'फ़ोटो खींचें',
  'upload_gallery': 'गैलरी से अपलोड करें',
  'analyzing_issue': 'समस्या का विश्लेषण...',
  'ai_result': 'विश्लेषण परिणाम',
  'detected_issue': 'पहचानी गई समस्या',
  'department': 'विभाग',
  'priority': 'प्राथमिकता',
  'confidence': 'विश्वसनीयता',
  'description': 'विवरण',
  'add_notes': 'अतिरिक्त नोट जोड़ें...',
  'confirm_location': 'स्थान पुष्टि करें',
  'adjust_pin': 'स्थान समायोजित करने के लिए पिन खींचें',
  'add_landmark': 'लैंडमार्क जोड़ें (वैकल्पिक)',
  'complaint_draft': 'शिकायत सारांश',
  'generate_qr': 'QR कोड जनरेट करें',
  'save_draft': 'ड्राफ़्ट सहेजें',
  'qr_instructions': 'कियोस्क सबमिशन',
  'qr_message': 'इस शिकायत को दर्ज करने के लिए, निकटतम कियोस्क पर जाएं और QR कोड स्कैन करें।',
  'regenerate_qr': 'QR पुनः जनरेट करें',
  'retake_photo': 'फ़ोटो दोबारा लें',

  // Complaints
  'all_complaints': 'सभी',
  'pending': 'लंबित',
  'in_progress': 'प्रगति में',
  'resolved': 'समाधान हुआ',
  'draft': 'ड्राफ़्ट',
  'no_complaints': 'अभी कोई शिकायत नहीं',
  'complaint_details': 'शिकायत विवरण',
  'timeline': 'समयरेखा',

  // Profile
  'name': 'नाम',
  'mobile_number': 'मोबाइल नंबर',
  'address': 'पता',
  'edit_profile': 'प्रोफ़ाइल संपादित करें',
  'change_language': 'भाषा बदलें',
  'logout': 'लॉगआउट',
  'logout_confirm': 'क्या आप वाकई लॉगआउट करना चाहते हैं?',

  // Chatbot
  'chatbot_greeting': 'नमस्ते! मैं आपका URBAN सहायक हूं। मैं आज आपकी कैसे मदद कर सकता हूं?',
  'type_message': 'संदेश लिखें...',
};
